### ISSUE TITLE
Outdated server component

### ISSUE THREAD

**Issue by kragil** [defold/game-xoxo-nakama-server#2]
As per https://forum.heroiclabs.com/t/ways-to-debug-server-code-nakama-defold-tictactoe-xoxo-example/3492/8
this code is outdated. 

Could you update the code and the corresponding blog entries? Pretty please. ;-)

**Comment by kragil** [comment]
Strange thing that game still works on the web .. or is that also running an old server version?

**Comment by kragil** [comment]
Pull request waiting B-)

**Comment by britzl** [comment]
> Pull request waiting B-)

Merged!

> update the code and the corresponding blog

Since the default behaviour is to not do anything with the `match_signal` it doesn't make sense to mention it specifically in the blog post.
